### ISSUE TITLE
Erste LED wird nicht angesteuert

### ISSUE THREAD

**Issue by Bert-wbs** [SIGSEGV111/ws281x-spi-driver#2]
Hallo SIGSEGV111,
ich habe mir den ws281x-spi-Treiber heruntergeladen und getestet.
Erst mal herzlichen Dank für deine Arbeit.
Bei mir ist es so, bei allen enthaltenden Demos und meiner eigenen main,
dass die erste LED nicht angesteuert wird.
arr_pixels[0] wird als zweite LED angesteuert.
Dann geht alles der Reihe nach und so wie es sein sollte.
Der Streifen ist nicht defekt. Bei python Beispielen wird auch die erste LED angesteuert.
Was kann das sein?
Herzlichen Dank schon mal

**Comment by SIGSEGV111** [comment]
Hallo Bert,

Glaube das Problem hatte ich so noch nie.
Machst Du das Ganze auf einem Raspberry Pi oder einem anderem System?
Wie hast Du die LEDs bei Dir mit Strom versorgt? 5V oder 3,3V? Externes Netzteil?
Irgendein Level-Shifter zwischendrin?

Kannst Du mal versuchen die Variable "uint8_t latch_delay[2];" in "TNeoPixel" auszukommentieren? Die sollte technisch nicht gebraucht werden.
Oder HZ_SPI_NEOPIXEL mal ein bisschen zu verändern (+-10%).
Evt. hilft auch ein Pullup-Widerstand (ca. 4k-10k auf 3,3V).

Lass mich wissen ob das geholfen hat.

Grüße
Simon

**Comment by Bert-wbs** [comment]
Hallo Simon,
in meiner ersten Anfrage habe ich dir leider nicht alle Infos zukommen lassen. Sorry.
Ich verwende einen Raspberry 4+ mit 4GB Ram  Version (uname -r) 5.10.27-v7l
Die LEDs werden mit 5V externes Netzteil angeschlossen. 
GND Netzteil und GND Raspberry sind verbunden.
Als Levelshifter setze ich einen kleinen RUNCCI-YUN 15x 4-Kanal Pegelwandler Logic ein.
Der funktioniert ansonsten sehr gut.

Ich habe folgende getestet:
1. Variable "uint8_t latch_delay[2] auskommentiert   - Ergebnis leider dasselbe
2. HZ_SPI_NEOPIXEL verändert zwischen 2000000 und 3000000 - Ergebnis leider dasselbe
3. Pullup R zwischen GPIO 10 (MOSI) Ausgang zum Levelshifter 10 K  - Ergebnis leider dasselbe

Wenn ich mit z.B mit einem python-sript "alle" Leds anschalte, werden auch mit dem script "off" nur ab der 2. LED alle Leds gelöscht.
Kann ich irgendwie die Daten (spi_dev_1.SendData(arr_pixels)  auf dem Bildschirm sichtbar machen und auswerten, um auf den Fehler zu kommen?
Vielleicht hast du ja noch eine Idee.

Viele Grüsse
Wigbert

**Comment by SIGSEGV111** [comment]
Hi Wigbert,

Sorry für die späte Antwort.
Der Pegelwandler ist eiegntlich für I2C (~100 KHz) gedacht. Die LEDs laufen mit 2500 KHz.
Kannst Du mal versuchen die LEDs via 3,3V vom Raspberry zu versorgen - dann brauchst Du den Level-Shifter nicht mehr.
Das Ganze hat natürlich starke Limitierungen - weniger Helligkeit und nur wenige LEDs, aber zum Testen wäre es gut da wir dadurch eine Fehlerquelle ausschließen können.

Bzgl. dem Array... nun Du kannst es Dir z.B. hexadezimal ausgeben lassen.
Hier ist ein Beispiel: https://stackoverflow.com/a/29865

Aber eigentlich bäruchtest Du jetzt ein Oszilloskop um wirklich zu sehen was der Rasperry über die Leitung rausschickt - bzw. was der Level-Shifter draus macht.

Grüße
Simon

**Comment by Bert-wbs** [comment]
Hallo Simon,

dein Hinweis zum Pegelwandler war der richtige Tipp.

Jetzt habe ich als Level shifter einen 74HCT125 geschaltet.

Jetzt geht es.

Was auch geht ist bei der LED Versorgung von 3.3V und ohne Pegelwandler.

 

Also es läuft jetzt.

Herzlichen Dank und einen schönen Abend

Grüße

Wigbert, 

 

Von: SIGSEGV ***@***.***> 
Gesendet: Dienstag, 20. April 2021 13:45
An: SIGSEGV111/ws281x-spi-driver ***@***.***>
Cc: Bert-wbs ***@***.***>; Author ***@***.***>
Betreff: Re: [SIGSEGV111/ws281x-spi-driver] Erste LED wird nicht angesteuert (#2)

 

Hi Wigbert,

Sorry für die späte Antwort.
Der Pegelwandler ist eiegntlich für I2C (~100 KHz) gedacht. Die LEDs laufen mit 2500 KHz.
Kannst Du mal versuchen die LEDs via 3,3V vom Raspberry zu versorgen - dann brauchst Du den Level-Shifter nicht mehr.
Das Ganze hat natürlich starke Limitierungen - weniger Helligkeit und nur wenige LEDs, aber zum Testen wäre es gut da wir dadurch eine Fehlerquelle ausschließen können.

Bzgl. dem Array... nun Du kannst es Dir z.B. hexadezimal ausgeben lassen.
Hier ist ein Beispiel: https://stackoverflow.com/a/19047008

Aber eigentlich bäruchtest Du jetzt ein Oszilloskop um wirklich zu sehen was der Rasperry über die Leitung rausschickt - bzw. was der Level-Shifter draus macht.

Grüße
Simon

**Comment by SIGSEGV111** [comment]
Hi Wigbert,

Super das es geklappt hat!
Ich nehme das mal besser mit auf in der Dokumentation....

Danke & Grüße
Simon

**Comment by Bert-wbs** [comment]
Hallo Simon,
super, du hast ja die Doku schon geändert.
Das wird sicher dem Einen oder Anderen helfen. Danke.
Ich habe aber noch eine Frage an dich.
Wäre es möglich den Aufruf "arr_pixels[i].RGB(rt, gn, bl);" dahingehend zu ergänzen bzw einen neuen zu erstellen, bei dem 
die Helligkeit der LEDs in einem ersten Wert angegeben werden kann. 
Hintergrund bei geringer Helligkeit (ca. 50 oder weniger) sind die Spektrum Farben eingeschränkt.
Will man zB. einen Regenbogen darstellen wäre es besser, die einzelnen Farben mit 0-255 anzugeben und separat die
Helligkeit zu steuern.
Beispiel: arr_pixels[i].RGB(Helligkeit, rt, gn, bl);
Helligkeit: 0-255, rt,gn,bl, = 0-255;
Oder ist diese Lösung in deinem Projekt bereits integriert und sich habe sie nicht gefunden?

Herzlichen Dank für deine Hilfe
MFG
Wigbert

**Comment by SIGSEGV111** [comment]
Am Montag, 26. April 2021, 14:42:53 CEST schrieb Bert-wbs:
> Hallo Simon,
> super, du hast ja die Doku schon geändert.
> Das wird sicher dem Einen oder Anderen helfen. Danke.
> Ich habe aber noch eine Frage an dich.
> Wäre es möglich den Aufruf "arr_pixels[i].RGB(rt, gn, bl);" dahingehend zu
> ergänzen bzw einen neuen zu erstellen, bei dem 
 die Helligkeit der LEDs in
> einem ersten Wert angegeben werden kann. Hintergrund bei geringer
> Helligkeit (ca. 50 oder weniger) sind die Spektrum Farben eingeschränkt.
> Will man zB. einen Regenbogen darstellen wäre es besser, die einzelnen
> Farben mit 0-255 anzugeben und separat die Helligkeit zu steuern.
> Beispiel: arr_pixels[i].RGB(Helligkeit, rt, gn, bl);
> Helligkeit: 0-255, rt,gn,bl, = 0-255;
> Oder ist diese Lösung in deinem Projekt bereits integriert und sich habe sie
> nicht gefunden?
 
> Herzlichen Dank für deine Hilfe
> MFG
> Wigbert 
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/SIGSEGV111/ws281x-spi-driver/issues/2#issuecomment-826804
> 004

Hi Wigbert,

Das Problem liegt hier leider bei den LEDs.
Im niedrigen Integer-Bereich ist das Farbspektrum sehr eingeschränkt.
Die RGB-Werte werden 1:1 an die LEDs durchgereicht. Soweit ich weiß gibt es 
keine Möglichkeit eine Helligkeit mit zu senden (oder gar Float-Zahlen zu 
verwenden).

Ich hatte in einem Projekt deswegen mal mehrere LEDs per Software zu einer 
virtuellen LED zusammengeschaltet um mehr Farbauflösung zu bekommen.
Habe dazu aber leider kein Codebeispiel online....

Dazu kommt noch, das die Integer-Werte die Energie des ausgesendeten Lichtes 
widerspiegeln und nicht die wahrgenommene Helligkeit. Es gibt dazu 
Korrekturformeln online [1] . Allerdings fand ich die wenig hilfreich aufgrund 
der geringen Auflösung von 8bit.

[1] https://learn.adafruit.com/led-tricks-gamma-correction
(den Teil bzgl. PROGMEM kannst Du auf dem RPi ignorieren)

-- 
Mit freundlichen Grüße
Simon Brennecke

**Comment by Bert-wbs** [comment]
Hallo Simon,
Sorry für die späte Rückmeldung.
Ich hatte leider keine Mail diesbezüglich bekommen.
Danke für deine Antwort.
Schade das es so nicht geht.
Aber macht nicht.
Viele Grüße
Wigbert
